#!/usr/bin/env python3
"""Generate the 2^r near-minimax polynomial coefficients for vexp_f32"""
from __future__ import annotations

import argparse
import logging
import struct
import sys
from pathlib import Path

import numpy as np
from numpy.polynomial import chebyshev as Cheb

DEGREE = 6
SAMPLES = 1024
RMIN = -0.5
RMAX = +0.5

log = logging.getLogger("gen_exp_coeffs")


def fit_minimax(degree, samples, rmin, rmax):
    k = np.arange(samples, dtype=np.float64)
    x = np.cos((2.0 * k + 1.0) * np.pi / (2.0 * samples))
    r = 0.5 * (rmax - rmin) * x + 0.5 * (rmax + rmin)
    y = np.exp2(r)
    cheb = Cheb.chebfit(r, y, degree)
    power = Cheb.cheb2poly(cheb)
    poly = np.polynomial.Polynomial(power)
    err = float(np.max(np.abs(poly(r) - y)))
    return power, err


def as_f32_bits(value: float) -> int:
    return struct.unpack("<I", struct.pack("<f", np.float32(value)))[0]


def emit_header(path: Path, degree: int, coeffs, rmin: float, rmax: float,
                err: float):
    lines = [
        "// exp_coeffs.h",
        "// AUTO-GENERATED by tools/gen_exp_coeffs.py -- do not edit.",
        f"// degree={degree}  range=[{rmin:+.3f},{rmax:+.3f}]  maxerr={err:.3e}",
        "//",
        "// The coefficients are fp32 bit patterns: the vector hart has",
        "// no DRAM route, so the values must stay integer immediates.",
        "",
        "#ifndef EXP_COEFFS_H",
        "#define EXP_COEFFS_H",
        "",
        "#include <cstdint>",
        "",
        "namespace exp_coeffs {",
        "",
        f"inline constexpr int kDegree = {degree};",
    ]
    for i, c in enumerate(coeffs):
        bits = as_f32_bits(c)
        lines.append(f"inline constexpr std::uint32_t kC{i} = "
                     f"0x{bits:08X}u;  // {c:+.10e}f")
    lines += ["", "}  // namespace exp_coeffs", "", "#endif", ""]
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--degree", type=int, default=DEGREE)
    p.add_argument("--samples", type=int, default=SAMPLES)
    p.add_argument("--rmin", type=float, default=RMIN)
    p.add_argument("--rmax", type=float, default=RMAX)
    p.add_argument("--out", type=Path, default=Path("exp_coeffs.h"))
    args = p.parse_args()

    coeffs, err = fit_minimax(args.degree, args.samples, args.rmin,
                              args.rmax)
    emit_header(args.out, args.degree, coeffs, args.rmin, args.rmax, err)
    log.warning(f"wrote {args.out} (degree={args.degree}, "
                f"max|err|={err:.3e})")


if __name__ == "__main__":
    logging.basicConfig(level=logging.WARNING, format="%(message)s")
    sys.exit(main())
